# docker run --name api-solid-rs-pg -e POSTGRESQL_USERNAME=docker POSTGRESQL_PASSWORD=docker POSTGRESQL_DATABASE=apisolid 
# -p 5432:5432 bitnami/postgresql

version: '3'

services:
  api-solid-rs-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid

